# Generated by Django 2.2.6 on 2019-11-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191027_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='comments_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
    ]
