# Generated by Django 2.2.6 on 2019-10-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_ads_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityOfViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_views', models.IntegerField()),
                ('link_to_hidden_ad', models.TextField()),
            ],
        ),
    ]
